### ISSUE TITLE
 java.lang.IllegalStateException: Fragment already added: 

### ISSUE THREAD

**Issue by muigukenneth** [ahmadnajar10/fancyDialog#11]
```
Fatal Exception: java.lang.IllegalStateException: Fragment already added: FancyAlertDialog{41d19b48 #0 FancyAlertDialog}
       at android.support.v4.app.FragmentManagerImpl.addFragment(FragmentManager.java:1679)
       at android.support.v4.app.BackStackRecord.executeOps(BackStackRecord.java:727)
       at android.support.v4.app.FragmentManagerImpl.executeOps(FragmentManager.java:2363)
       at android.support.v4.app.FragmentManagerImpl.executeOpsTogether(FragmentManager.java:2149)
       at android.support.v4.app.FragmentManagerImpl.optimizeAndExecuteOps(FragmentManager.java:2103)
       at android.support.v4.app.FragmentManagerImpl.execPendingActions(FragmentManager.java:2013)
       at android.support.v4.app.FragmentManagerImpl$1.run(FragmentManager.java:710)
```

**When does it happen**: when you show multiple Fancy Dialogs without dismissing  the previous ones.
**Possible Solution** :Add a check if !isAdded() on show dialog.

Cheers for this awesome library.

**Comment by a-najar** [comment]
fixed this issue please upgrade and test

**Comment by muigukenneth** [comment]
Thanks, Its fixed now. 😃
