### ISSUE TITLE
Crash on Button Click if Application Paused

### ISSUE THREAD

**Issue by rayliverified** [ahmadnajar10/fancyDialog#12]
App crashes on button press if application is paused. Fancy Dialog Builder does not save click objects so they become null. 
```
04-08 14:57:53.250 29392-29392/com.geniusforapp.fancysample E/AndroidRuntime: FATAL EXCEPTION: main
                                                                              Process: com.geniusforapp.fancysample, PID: 29392
                                                                              java.lang.NullPointerException: Attempt to invoke virtual method 'com.geniusforapp.fancydialog.FancyAlertDialog$OnPositiveClicked com.geniusforapp.fancydialog.FancyAlertDialog$Builder.getOnPositiveClicked()' on a null object reference
                                                                                  at com.geniusforapp.fancydialog.FancyAlertDialog$1.onClick(FancyAlertDialog.java:140)
                                                                                  at android.view.View.performClick(View.java:5201)
                                                                                  at android.view.View$PerformClick.run(View.java:21215)
                                                                                  at android.os.Handler.handleCallback(Handler.java:739)
                                                                                  at android.os.Handler.dispatchMessage(Handler.java:95)
                                                                                  at android.os.Looper.loop(Looper.java:148)
                                                                                  at android.app.ActivityThread.main(ActivityThread.java:5525)
                                                                                  at java.lang.reflect.Method.invoke(Native Method)
                                                                                  at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:730)
                                                                                  at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:620)
```

**Comment by rayliverified** [comment]
Problem fixed after a lot of research. There is not much info about saving Builder states. 
Adding changes to library for testing.
