### ISSUE TITLE
Can not perform this action after onSaveInstanceState

### ISSUE THREAD

**Issue by amarilindra** [ahmadnajar10/fancyDialog#22]
I'm seeing this crash many times in my crashlytics. I can not reproduce it on my device though. 
Any idea why only a few users are seeing this crash? (My app orientation is set to Portrait) 

Fatal Exception: java.lang.IllegalStateException: Can not perform this action after onSaveInstanceState
       at android.support.v4.app.FragmentManagerImpl.checkStateLoss(Unknown Source)
       at android.support.v4.app.FragmentManagerImpl.modifiesAlpha(Unknown Source)
       at android.support.v4.app.BackStackRecord.dump(Unknown Source)
       at android.support.v4.app.BackStackRecord.commit(Unknown Source)
       at android.support.v4.app.DialogFragment.show(Unknown Source)
       at ikvaesolutions.xxxxxxxxxxx.custom.FancyAlertDialog.onCreate(Unknown Source)
       at ikvaesolutions.xxxxxxxxxxx.custom.FancyAlertDialog.onCreate(Unknown Source)
       at ikvaesolutions.xxxxxxxxxxx.custom.FancyAlertDialog$Builder.show(Unknown Source)
       at ikvaesolutions.xxxxxxxxxxx.activities.SplashScreenActivity.showDisclaimer(Unknown Source)
       at ikvaesolutions.xxxxxxxxxxx.activities.SplashScreenActivity.access$000(Unknown Source)
       at ikvaesolutions.xxxxxxxxxxx.activities.SplashScreenActivity$1.run(Unknown Source)
       at android.os.Handler.handleCallback(Handler.java:739)
       at android.os.Handler.dispatchMessage(Handler.java:95)
       at android.os.Looper.loop(Looper.java:148)
       at android.app.ActivityThread.main(ActivityThread.java:5530)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:733)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:623)

**Comment by cwbsl** [comment]
This error still occurs. It could be fixed by modifying the show() method inside the FancyAlertDialog.java class like described here:
https://stackoverflow.com/a/35431196/754730

**Comment by a-najar** [comment]
@amarilindra you could update to the new version in the releases
